### ISSUE TITLE
Write top menu entries

### ISSUE THREAD

**Issue by celedev97** [fc-dev/GitNarwhal#3]
The top menubar should have some well tought submenu/entries instead of default and useless one, look at sourcetree/gitkraken for ideas

**NOTE:** keep in mind that the client won't have an editor like gitkraken so it's useless to have undo/redo-like features

**Comment by dag7dev** [comment]
As of now, the entire SourceTree top menu bar has been implemented.

- What sections and options should be removed?
- Do we have to use the same keyboard shortcuts (or let the user define itself by integrating a kind of editor / editing xml file / loading values from somewhere?)
