### ISSUE TITLE
Tab for cloning/creating repo

### ISSUE THREAD

**Issue by celedev97** [fc-dev/GitNarwhal#4]
There should be an FXML control for a newly-created tab that has components to allow repo initialization/cloning

**NOTE:** still too early for online repo creation, ignore that for now.

- [x] FXML
- [x] Controller
- [ ] Functionality

**Comment by dag7dev** [comment]
GUI has been implemented: https://github.com/fc-dev/GitNarwhal/commit/4ec2a8d7433a463c9073aafaa2bd8f4e72d5962f
